name: gulp-bs
recipe: drupal8

proxy:
  node:
    - bs.gulp-bs.lndo.site:3000

config:
  via: nginx
  webroot: web
  php: 7.3
  database: mariadb:10.3

services:
  appserver:
    run:
      - "cd $LANDO_MOUNT && composer install"
  node:
    type: node:12
    run:
      - cd /app/web/themes/contrib/bootstrap_sass && yarn
    command: cd /app/web/themes/contrib/bootstrap_sass && node_modules/.bin/gulp serve 

tooling:
  node:
    service: node
    cmd: node
  yarn:
    service: node
    cmd: yarn
  gulp:
    service: node
    cmd: gulp
